CREATE DATABASE JOB_INTERVIEW;

USE JOB_INTERVIEW;

CREATE TABLE TEST_TABLE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  TERM_ID VARCHAR(255),
  BRANCH VARCHAR(255),
  VENDORNO VARCHAR(255),
  PRODUCTNO VARCHAR(255),
  PMINO VARCHAR(255),
  BATCH INT,
  SLIPNO INT,
  TERM_NAME VARCHAR(255),
  TERM_FOOD VARCHAR(255),
  PAYPERCENT FLOAT,
  PAYPERDAY FLOAT,
  INCLUDEVAT VARCHAR(255),
  INV_PRINT VARCHAR(255),
  INV_NAME VARCHAR(255),
  INV_ADDR VARCHAR(255),
  TERM_FLAG VARCHAR(255),
  TYPEPAY VARCHAR(255),
  STAFFOFCHARGE FLOAT,
  STAFFPRODUCTNO VARCHAR(255),
  CUSTOMER_REF VARCHAR(255),
  RENTAL_ID VARCHAR(255),
  HORIZON_SENT VARCHAR(255),
  LEASE_TYPE VARCHAR(255),
  CLUBCARD_CODE VARCHAR(255),
  CLUBCARD_AMT FLOAT,
  CLUBCARD_POINT INT,
  TERMINAL_TYPE VARCHAR(255)
);

INSERT INTO TEST_TABLE 
(TERM_ID, BRANCH, VENDORNO, PRODUCTNO, PMINO, BATCH, SLIPNO, TERM_NAME, TERM_FOOD, PAYPERCENT, PAYPERDAY, INCLUDEVAT, INV_PRINT, INV_NAME, INV_ADDR, TERM_FLAG, TYPEPAY, STAFFOFCHARGE, STAFFPRODUCTNO, CUSTOMER_REF, RENTAL_ID, HORIZON_SENT, LEASE_TYPE, CLUBCARD_CODE, CLUBCARD_AMT, CLUBCARD_POINT, TERMINAL_TYPE)
VALUES 
('1001', 'Branch A', 'V001', 'P001', 'PM001', 1, 1, 'Terminal 1', 'Food', 5, 30, 'Yes', 'Yes', 'John Smith', '123 Main St.', 'No', 'Visa', 10.00, 'P001', 'C001', 'R001', '2022-01-01', 'Lease', 'C001', 10.00, 100, 'Type A')
